"""empty message

Revision ID: 3329ade8cebf
Revises: 8b698f9e963f
Create Date: 2024-11-13 19:28:55.557312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3329ade8cebf'
down_revision = '8b698f9e963f'
branch_labels = None
depends_on = None


def upgrade():
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('module', schema=None) as batch_op:
    #     batch_op.add_column(sa.Column('constant', sa.String(length=64), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('module', schema=None) as batch_op:
        batch_op.drop_column('constant')

    # ### end Alembic commands ###
