"""empty message

Revision ID: 383e7656f8e4
Revises: c198e4c92b20
Create Date: 2024-09-06 10:20:42.509607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '383e7656f8e4'
down_revision = 'c198e4c92b20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('challenge', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('challenge', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
