"""empty message

Revision ID: 534cbcc7a66a
Revises: b506a7852b7d
Create Date: 2024-11-11 10:44:32.860612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '534cbcc7a66a'
down_revision = 'b506a7852b7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_superuser', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_superuser')

    # ### end Alembic commands ###
