"""empty message

Revision ID: 5fad40cef84c
Revises: 7d8c7877cd92
Create Date: 2024-11-12 09:51:16.878474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fad40cef84c'
down_revision = '7d8c7877cd92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('code_challenge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('flag', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('vuln_code', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('code_challenge', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_code_challenge_name'), ['name'], unique=False)

    op.create_table('user_codechallenge_completions',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('challenge_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['code_challenge.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'challenge_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_codechallenge_completions')
    with op.batch_alter_table('code_challenge', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_code_challenge_name'))

    op.drop_table('code_challenge')
    # ### end Alembic commands ###
