"""empty message

Revision ID: b506a7852b7d
Revises: 383e7656f8e4
Create Date: 2024-09-06 10:23:31.950357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b506a7852b7d'
down_revision = '383e7656f8e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('challenge', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))
        batch_op.drop_index('ix_challenge_name')
        batch_op.create_index(batch_op.f('ix_challenge_name'), ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('challenge', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_challenge_name'))
        batch_op.create_index('ix_challenge_name', ['name'], unique=1)
        batch_op.drop_column('description')

    # ### end Alembic commands ###
