"""empty message

Revision ID: e5f943317709
Revises: 63523d82bb25
Create Date: 2024-11-12 09:09:06.679842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5f943317709'
down_revision = '63523d82bb25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_codechallenge_completions')
    op.drop_table('code_challenges')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('code_challenges',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('flag', sa.VARCHAR(), nullable=False),
    sa.Column('vuln_code', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_codechallenge_completions',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('challenge_id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
