FROM php:apache
COPY upload.php upload.php
COPY problem.php problem.php
COPY verify.php verify.php
COPY challenge.php challenge.php
RUN apt-get update && apt-get install -y iputils-ping
EXPOSE 80
EXPOSE 443
