version: '3'
services:
  www:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - 80:80
      - 443:443
    command: /bin/sh -c "chown www-data:www-data /var/www/html/problem.php && chmod +w /var/www/html/problem.php && apache2-foreground"